server:
  port: 9099

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306?&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: brian
    driverClassName: com.mysql.cj.jdbc.Driver  
    type: com.zaxxer.hikari.HikariDataSource
    dbcp2:
      validation-query: SELECT 1
    hikari:      
      maximum-pool-size: 50
      #minimum-idle: 100
      max-lifetime: 60000 #1800000
      connection-timeout: 30000 #30000
      validation-timeout: 5000
      #connection-test-query: SELECT 1      
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

  
    
  
  jpa:  
    show-sql: false
    #database-platform: org.hibernate.dialect.MySQL5Dialect    
    hibernate:    
      ddl-auto: none #create 로 해놓으면 Data전체 삭제 됨. 개발 초기에는 update 사용하나 상용에는 none 필수.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl